/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SearcherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// search.ts
var SEARCH_ENGINES = {
  google: "https://www.google.com/search?q=",
  bing: "https://www.bing.com/search?q=",
  baidu: "https://www.baidu.com/s?wd=",
  duckduckgo: "https://duckduckgo.com/?q=",
  yahoo: "https://search.yahoo.com/search?p="
};
var DEFAULT_SETTINGS = {
  engineId: "google",
  customUrl: "https://www.google.com/search?q={query}"
};
var QUERY_PLACEHOLDER = "{query}";
function isPresetSearchEngineId(value) {
  return typeof value === "string" && value in SEARCH_ENGINES;
}
function validateSearchTemplate(template) {
  if (!template.trim()) return false;
  try {
    const url = new URL(template.split(QUERY_PLACEHOLDER).join("query"));
    return url.protocol === "https:" || url.protocol === "http:";
  } catch (e) {
    return false;
  }
}
function buildSearchUrl(settings, query) {
  const encodedQuery = encodeURIComponent(query);
  const template = settings.engineId === "custom" ? settings.customUrl.trim() : SEARCH_ENGINES[settings.engineId];
  const url = template.includes(QUERY_PLACEHOLDER) ? template.split(QUERY_PLACEHOLDER).join(encodedQuery) : `${template}${encodedQuery}`;
  return validateSearchTemplate(url) ? url : null;
}
function normalizeSettings(data) {
  var _a;
  if (!isRecord(data)) return { ...DEFAULT_SETTINGS };
  if (isPresetSearchEngineId(data.engineId)) {
    return {
      engineId: data.engineId,
      customUrl: (_a = getValidCustomUrl(data.customUrl)) != null ? _a : DEFAULT_SETTINGS.customUrl
    };
  }
  if (data.engineId === "custom") {
    const customUrl = getValidCustomUrl(data.customUrl);
    if (customUrl) return { engineId: "custom", customUrl };
  }
  if (typeof data.searchEngine === "string") {
    const preset = getPresetIdByUrl(data.searchEngine);
    if (preset) return { engineId: preset, customUrl: DEFAULT_SETTINGS.customUrl };
    const customUrl = getValidCustomUrl(data.searchEngine);
    if (customUrl) return { engineId: "custom", customUrl };
  }
  return { ...DEFAULT_SETTINGS };
}
function getPresetIdByUrl(url) {
  for (const [id, presetUrl] of Object.entries(SEARCH_ENGINES)) {
    if (url === presetUrl) return id;
  }
  return null;
}
function getValidCustomUrl(value) {
  if (typeof value !== "string") return null;
  const url = value.trim();
  return validateSearchTemplate(url) ? url : null;
}
function isRecord(value) {
  return typeof value === "object" && value !== null;
}

// main.ts
var ENGLISH_MESSAGES = {
  commandName: "Search selected text on the web",
  menuItem: "Search on the web",
  emptySelection: "Select text to search first.",
  invalidTemplate: "The custom search URL must be a valid HTTP(S) URL.",
  couldNotOpen: "Could not open the search result in your browser.",
  settingsHeading: "Searcher settings",
  searchEngineName: "Search engine",
  searchEngineDescription: "Choose the search engine used for selected text.",
  customEngine: "Custom",
  customUrlName: "Custom search URL",
  customUrlDescription: "Use {query} to place the encoded search text. Without it, the text is appended to the URL.",
  customUrlPlaceholder: "https://www.google.com/search?q={query}",
  invalidCustomUrl: "Enter a valid HTTP(S) URL.",
  usageHeading: "Usage",
  usageDescription: "Select text in an editor, then use the context menu or command palette to search the web."
};
var CHINESE_MESSAGES = {
  commandName: "\u5728\u7F51\u7EDC\u4E0A\u641C\u7D22\u9009\u4E2D\u6587\u5B57",
  menuItem: "\u5728\u7F51\u7EDC\u4E0A\u641C\u7D22",
  emptySelection: "\u8BF7\u5148\u9009\u4E2D\u8981\u641C\u7D22\u7684\u6587\u5B57\u3002",
  invalidTemplate: "\u81EA\u5B9A\u4E49\u641C\u7D22 URL \u5FC5\u987B\u662F\u6709\u6548\u7684 HTTP(S) \u5730\u5740\u3002",
  couldNotOpen: "\u65E0\u6CD5\u5728\u6D4F\u89C8\u5668\u4E2D\u6253\u5F00\u641C\u7D22\u7ED3\u679C\u3002",
  settingsHeading: "Searcher \u63D2\u4EF6\u8BBE\u7F6E",
  searchEngineName: "\u641C\u7D22\u5F15\u64CE",
  searchEngineDescription: "\u9009\u62E9\u7528\u4E8E\u641C\u7D22\u9009\u4E2D\u6587\u5B57\u7684\u641C\u7D22\u5F15\u64CE\u3002",
  customEngine: "\u81EA\u5B9A\u4E49",
  customUrlName: "\u81EA\u5B9A\u4E49\u641C\u7D22 URL",
  customUrlDescription: "\u4F7F\u7528 {query} \u63D2\u5165\u7F16\u7801\u540E\u7684\u641C\u7D22\u6587\u5B57\u3002\u672A\u4F7F\u7528\u65F6\uFF0C\u6587\u5B57\u4F1A\u8FFD\u52A0\u5230 URL \u672B\u5C3E\u3002",
  customUrlPlaceholder: "https://www.google.com/search?q={query}",
  invalidCustomUrl: "\u8BF7\u8F93\u5165\u6709\u6548\u7684 HTTP(S) URL\u3002",
  usageHeading: "\u4F7F\u7528\u8BF4\u660E",
  usageDescription: "\u5728\u7F16\u8F91\u5668\u4E2D\u9009\u4E2D\u6587\u5B57\uFF0C\u7136\u540E\u4F7F\u7528\u53F3\u952E\u83DC\u5355\u6216\u547D\u4EE4\u9762\u677F\u8FDB\u884C\u7F51\u7EDC\u641C\u7D22\u3002"
};
function getMessages() {
  return (0, import_obsidian.getLanguage)().toLowerCase().startsWith("zh") ? CHINESE_MESSAGES : ENGLISH_MESSAGES;
}
var SearcherPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    await this.loadSettings();
    this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor) => {
      const selectedText = editor.getSelection();
      if (!selectedText.trim()) return;
      menu.addItem((item) => item.setTitle(getMessages().menuItem).setIcon("search").onClick(() => this.searchOnWeb(selectedText)));
    }));
    this.addCommand({
      id: "search-selected-text",
      name: getMessages().commandName,
      editorCallback: (editor) => this.searchOnWeb(editor.getSelection())
    });
    this.addSettingTab(new SearcherSettingTab(this.app, this));
  }
  searchOnWeb(text) {
    const query = text.trim();
    if (!query) {
      new import_obsidian.Notice(getMessages().emptySelection);
      return;
    }
    const searchUrl = buildSearchUrl(this.settings, query);
    if (!searchUrl) {
      new import_obsidian.Notice(getMessages().invalidTemplate);
      return;
    }
    try {
      window.open(searchUrl, "_blank", "noopener");
    } catch (e) {
      new import_obsidian.Notice(getMessages().couldNotOpen);
    }
  }
  async loadSettings() {
    this.settings = normalizeSettings(await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SearcherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const messages = getMessages();
    containerEl.empty();
    containerEl.createEl("h2", { text: messages.settingsHeading });
    new import_obsidian.Setting(containerEl).setName(messages.searchEngineName).setDesc(messages.searchEngineDescription).addDropdown((dropdown) => {
      for (const engineId of Object.keys(SEARCH_ENGINES)) {
        dropdown.addOption(engineId, engineId[0].toUpperCase() + engineId.slice(1));
      }
      dropdown.addOption("custom", messages.customEngine);
      dropdown.setValue(this.plugin.settings.engineId);
      dropdown.onChange(async (engineId) => {
        this.plugin.settings.engineId = engineId;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.engineId === "custom") {
      const customUrlSetting = new import_obsidian.Setting(containerEl).setName(messages.customUrlName).setDesc(messages.customUrlDescription).addText((text) => {
        text.setPlaceholder(messages.customUrlPlaceholder).setValue(this.plugin.settings.customUrl).onChange(async (value) => {
          const customUrl = value.trim();
          const isValid = validateSearchTemplate(customUrl);
          text.inputEl.setCustomValidity(isValid ? "" : messages.invalidCustomUrl);
          customUrlSetting.setDesc(isValid ? messages.customUrlDescription : messages.invalidCustomUrl);
          if (!isValid) return;
          this.plugin.settings.customUrl = customUrl;
          await this.plugin.saveSettings();
        });
      });
    }
    containerEl.createEl("h3", { text: messages.usageHeading });
    containerEl.createEl("p", { text: messages.usageDescription });
  }
};
