/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ResearcherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  searchEngine: "https://www.google.com/search?q="
};
var SEARCH_ENGINES = {
  "Google": "https://www.google.com/search?q=",
  "Bing": "https://www.bing.com/search?q=",
  "Baidu": "https://www.baidu.com/s?wd=",
  "DuckDuckGo": "https://duckduckgo.com/?q=",
  "Yahoo": "https://search.yahoo.com/search?p="
};
var ResearcherPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        const selectedText = editor.getSelection();
        if (selectedText && selectedText.trim().length > 0) {
          menu.addItem((item) => {
            item.setTitle("\u5728\u7F51\u7EDC\u4E0A\u641C\u7D22").setIcon("search").onClick(() => {
              this.searchOnWeb(selectedText);
            });
          });
        }
      })
    );
    this.addCommand({
      id: "search-selected-text",
      name: "\u5728\u7F51\u7EDC\u4E0A\u641C\u7D22\u9009\u4E2D\u6587\u5B57",
      editorCallback: (editor, view) => {
        const selectedText = editor.getSelection();
        if (selectedText && selectedText.trim().length > 0) {
          this.searchOnWeb(selectedText);
        } else {
          new import_obsidian.Notice("\u8BF7\u5148\u9009\u4E2D\u8981\u641C\u7D22\u7684\u6587\u5B57");
        }
      }
    });
    this.addSettingTab(new ResearcherSettingTab(this.app, this));
  }
  searchOnWeb(text) {
    const trimmedText = text.trim();
    if (!trimmedText)
      return;
    const searchUrl = this.settings.searchEngine + encodeURIComponent(trimmedText);
    window.open(searchUrl, "_blank");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ResearcherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Researcher \u63D2\u4EF6\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u641C\u7D22\u5F15\u64CE").setDesc("\u9009\u62E9\u7528\u4E8E\u641C\u7D22\u7684\u641C\u7D22\u5F15\u64CE").addDropdown((dropdown) => {
      for (const [name, url] of Object.entries(SEARCH_ENGINES)) {
        dropdown.addOption(url, name);
      }
      dropdown.addOption("custom", "\u81EA\u5B9A\u4E49");
      const currentValue2 = this.plugin.settings.searchEngine;
      const isPreset2 = Object.values(SEARCH_ENGINES).includes(currentValue2);
      dropdown.setValue(isPreset2 ? currentValue2 : "custom");
      dropdown.onChange(async (value) => {
        if (value !== "custom") {
          this.plugin.settings.searchEngine = value;
          await this.plugin.saveSettings();
          this.display();
        } else {
          this.plugin.settings.searchEngine = "https://www.google.com/search?q=";
          await this.plugin.saveSettings();
          this.display();
        }
      });
    });
    const currentValue = this.plugin.settings.searchEngine;
    const isPreset = Object.values(SEARCH_ENGINES).includes(currentValue);
    if (!isPreset) {
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49\u641C\u7D22\u5F15\u64CE URL").setDesc("\u8F93\u5165\u641C\u7D22\u5F15\u64CE\u7684URL\uFF08\u641C\u7D22\u5173\u952E\u8BCD\u4F1A\u9644\u52A0\u5728URL\u540E\u9762\uFF0C\u4F8B\u5982\uFF1Ahttps://www.google.com/search?q=\uFF09").addText((text) => {
        text.setPlaceholder("https://www.google.com/search?q=").setValue(currentValue).onChange(async (value) => {
          this.plugin.settings.searchEngine = value;
          await this.plugin.saveSettings();
        });
      });
    }
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    const desc = containerEl.createEl("p");
    desc.innerHTML = '\u5728\u7F16\u8F91\u5668\u4E2D\u9009\u4E2D\u6587\u5B57\uFF0C\u7136\u540E\u53F3\u952E\u70B9\u51FB\uFF0C\u5728\u5F39\u51FA\u7684\u83DC\u5355\u4E2D\u9009\u62E9"\u5728\u7F51\u7EDC\u4E0A\u641C\u7D22"\uFF0C\u5373\u53EF\u7528\u9ED8\u8BA4\u6D4F\u89C8\u5668\u6253\u5F00\u641C\u7D22\u7ED3\u679C\u9875\u9762\u3002';
  }
};
